version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    image: mkwarman/zcc-backend:0.1
    ports:
      - "4000:4000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: mkwarman/zcc-frontend:0.2
    ports:
      - "3000:80"